profile_name = "Rosaline"

[standard_materials]
"Bibo" = "/mt_c0201b0001_bibo.mtrl"
"Bibo Pubes" = "/mt_c0201b0001_bibopube.mtrl"
"BPF" = "/mt_c0201b0001_betterpube.mtrl"
"Neolithe Piercings Top" = "/mt_c0201b0001_neolithe_piercings_top.mtrl"
"Neolithe Piercings Bottom" = "/mt_c0201b0001_neolithe_piercings_bottom.mtrl"

[[groups]]
group_name = "Top"
mode = "exclusive"
[groups.shapekeys]
"MEDIUM (Basis)" = "Medium"
"LARGE" = "Large"
"ROCOCO" = "Coconut"
"FLAT" = "Flat"

[[groups]]
group_name = "Bottom"
mode = "optional"
[groups.shapekeys]
"Round Hips" = "Round Hips"
"Bulge" = "Bulge"

[[groups]]
group_name = "Body"
mode = "optional"
[groups.shapekeys]
"BUFF ARMS" = "Buff Arms"
