profile_name = "Rox"

[standard_materials]
"Bibo" = "/mt_c0201b0001_bibo.mtrl"
"Bibo Pubes" = "/mt_c0201b0001_bibopube.mtrl"
"BPF" = "/mt_c0201b0001_betterpube.mtrl"
"Bimbo Piercings" = "/mt_c0201b0001_bimbopierce.mtrl"

[[groups]]
group_name = "Top"
mode = "exclusive"
[groups.shapekeys]
"SMALL" = "Small"
"MEDIUM" = "Medium"
"LARGE" = "Large"
"COCONUT" = "Coconut"

[[groups]]
group_name = "Hips"
mode = "optional"
[groups.shapekeys]
"ROSEHIPS" = "Rosehip"
