profile_name = "Template"

[standard_materials]
"Bibo" = "/mt_c0201b0001_bibo.mtrl"
"Bibo Pubes" = "/mt_c0201b0001_bibopube.mtrl"
"BPF" = "/mt_c0201b0001_betterpube.mtrl"

[[groups]]
group_name = "Top"
mode = "exclusive"
[groups.shapekeys]
"Chest Large" = "Large"
"Chest Medium" = "Medium"
"Chest Small" = "Small"

[[groups]]
group_name = "Bottom"
mode = "exclusive"
[groups.shapekeys]
"Legs Large" = "Large"
"Legs Medium" = "Medium"
"Legs Small" = "Small"

[[groups]]
group_name = "Body"
mode = "optional"
[groups.shapekeys]
"Tummy" = "Tummy"

[export_aliases]
"Alt" = "Alt"

[incompatibilities]
Tummy = ["Legs Large", "Legs Medium"]